@startuml
digraph dfd {
    rankdir = LR;
    "954731510" [
        shape = none;margin=0;padding=0;
        label = 
        <
            <table border="1" cellspacing="0" cellborder="1">
                <tr>
                    <td colspan="3" border="0"><b>HotlineRetrieveTeleTAN</b>  </td>
                </tr>
                <tr>
                    <td colspan="3" sides="b">Actor.HealthAuthority</td>
                </tr>
                <tr>
                    <td border="0">teleTAN:</td>
                    <td border="0">Sensivity.Private</td>
                </tr>
            </table>
        >
    ];

    "48354135278" [
        shape = Mrecord;margin=0;padding=0;
        label = 
        <
            <table border="0" cellspacing="0" cellborder="1">
                <tr>
                    <td colspan="3" border="0"><b>GenerateTeleTAN</b>  </td>
                </tr>
                <tr>
                    <td colspan="3" sides="b">Actor.HealthAuthority</td>
                </tr>
                <tr>
                    <td border="0">&nbsp;teleTAN:</td>
                    <td border="0">Sensivity.Private </td>
                </tr>
                <tr>
                    <td border="0"></td>
                    <td border="0">Encryption.RSA </td>
                </tr>
            </table>
        >
    ];

    "934483247" [
        shape=none;margin=0;padding=0;label=
        <
            <table border="0" cellborder="1" sides="tlb">
                <tr>
                    <td width="120" height="26" sides="ltb"><b>UserDatabase</b></td>
                </tr>
            </table>
        >
    ];

    "123123123" [
        shape=none;margin=0;padding=0;label=
        <
            <table border="0" cellborder="1" sides="tlb">
                <tr>
                	<td border="1" sides="ltb"><b>DataStore</b>  </td>
                </tr>
                // title end
                // characteristics end
                // variables end
            </table>
        >
    ];


    "954731510" -> "48354135278";
    "48354135278" -> "934483247" [label="test"];
}
@enduml