@startuml
left to right direction

rectangle externalEntityID as "external entity U" {
    hexagon literalID1 as "literal X"
}

storage elementID1 as "process A" {
    hexagon literalID2 as "literal Y"
    artifact variableID1 as "variable A" {
        hexagon literalID4 as "literal W"
    }
}

storage elementID2 as "process B" {
    hexagon literalID3 as "literal Z"
}

database databaseID1 as "database F" {
    hexagon literalID5 as "literal V"
}

externalEntityID --> elementID1 : parameter A
elementID1 --> databaseID1 : parameter B
elementID1 --> elementID2 : parameter A
elementID2 --> databaseID1 : parameter C

@enduml